export const PATHS = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  leaderboard: "/leaderboard",
  achievements: "/achievements",
  settings: "/settings",
  tetrobots: "/tetrobots",
  tetrobotsHelp: "/tetrobots/help",
  tetrobotsRelations: "/tetrobots/relations",
  game: "/game",
  sprint: "/sprint",
  tetrisHub: "/tetris-hub",
  versus: "/versus",
  roguelike: "/roguelike",
  roguelikeVersus: "/roguelike-versus",
  roguelikeLexicon: "/roguelike/lexique",
  puzzle: "/puzzle",
  puzzleRun: "/puzzle/:id",
  brickfallSolo: "/brickfall-solo",
  brickfallSoloCommunity: "/brickfall-solo/community",
  brickfallSoloPlay: "/brickfall-solo/play",
  brickfallEditor: "/brickfall-editor",
  brickfallEditorHelp: "/brickfall/help/editor",
  tetroVerse: "/tetro-verse",
  tetromazeHub: "/tetromaze",
  tetromazeCommunity: "/tetromaze/community",
  tetromazePlay: "/tetromaze/play",
  tetromazeEditor: "/tetromaze/editor",
  tetromazeEditorHelp: "/tetromaze/help/editor",
  pixelProtocolHub: "/pixel-protocol",
  pixelProtocolCommunity: "/pixel-protocol/community",
  pixelProtocolCommunityLevel: "/pixel-protocol/community/:publishedId",
  pixelProtocolPlay: "/pixel-protocol/play",
  pixelProtocolEditor: "/pixel-protocol/editor",
  pixelProtocolEditorHelp: "/pixel-protocol/help/editor",
  pixelInvasion: "/pixel-invasion",
  notFound: "*",
} as const;

export const HIDE_NAVBAR_PATHS: ReadonlySet<string> = new Set([PATHS.login, PATHS.register]);
