// src/types/GameMode.ts
export enum GameMode {
  CLASSIQUE = "CLASSIQUE",
  SPRINT = "SPRINT",
  VERSUS = "VERSUS",
  BRICKFALL_VERSUS = "BRICKFALL_VERSUS",
  ROGUELIKE_VERSUS = "ROGUELIKE_VERSUS",
}
