import { describe, expect, it } from "vitest";
import { syncTetrobotProgressionState } from "./tetrobotProgressionLogic";

function createBaseStats() {
  return {
    botApexWins: 0,
    counters: {},
    level10Modes: {
      CLASSIQUE: false,
      SPRINT: false,
      VERSUS: false,
      BRICKFALL_SOLO: false,
      ROGUELIKE: false,
      ROGUELIKE_VERSUS: false,
      PUZZLE: false,
      TETROMAZE: false,
      PIXEL_INVASION: false,
    },
    lowestWinrateMode: "ROGUELIKE" as const,
    modesVisited: {
      CLASSIQUE: true,
      SPRINT: false,
      VERSUS: false,
      BRICKFALL_SOLO: false,
      ROGUELIKE: false,
      ROGUELIKE_VERSUS: false,
      PUZZLE: false,
      TETROMAZE: false,
      PIXEL_INVASION: false,
    },
    playerBehaviorByMode: {
      CLASSIQUE: { sessions: 4, wins: 1, losses: 3, totalDurationMs: 0, lastPlayedAt: null },
      SPRINT: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      VERSUS: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      BRICKFALL_SOLO: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      ROGUELIKE: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      ROGUELIKE_VERSUS: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      PUZZLE: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      TETROMAZE: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      PIXEL_INVASION: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
      PIXEL_PROTOCOL: { sessions: 0, wins: 0, losses: 0, totalDurationMs: 0, lastPlayedAt: null },
    },
    playerLongTermMemory: {
      recurringMistakes: [],
      avoidedModes: {},
      strongestModes: {},
      weakestModes: {},
      rageQuitCount: 0,
      comebackCount: 0,
      consistencyScore: 0,
      courageScore: 0,
      disciplineScore: 0,
    },
    playerMistakesByMode: {
      CLASSIQUE: {
        holes: 1,
        top_out: 1,
        slow: 0,
        unsafe_stack: 1,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      SPRINT: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      VERSUS: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      BRICKFALL_SOLO: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      ROGUELIKE: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      ROGUELIKE_VERSUS: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      PUZZLE: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      TETROMAZE: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      PIXEL_INVASION: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
      PIXEL_PROTOCOL: {
        holes: 0,
        top_out: 0,
        slow: 0,
        unsafe_stack: 0,
        damage_taken: 0,
        misread: 0,
        panic_stack: 0,
        slow_decision: 0,
        greedy_play: 0,
        mode_avoidance: 0,
        inconsistent_precision: 0,
      },
    },
    playerMistakeLastSeenByMode: {
      CLASSIQUE: {
        holes: 1,
        top_out: 2,
        slow: null,
        unsafe_stack: 3,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      SPRINT: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      VERSUS: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      BRICKFALL_SOLO: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      ROGUELIKE: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      ROGUELIKE_VERSUS: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      PUZZLE: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      TETROMAZE: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      PIXEL_INVASION: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
      PIXEL_PROTOCOL: {
        holes: null,
        top_out: null,
        slow: null,
        unsafe_stack: null,
        damage_taken: null,
        misread: null,
        panic_stack: null,
        slow_decision: null,
        greedy_play: null,
        mode_avoidance: null,
        inconsistent_precision: null,
      },
    },
    scoredModes: {
      CLASSIQUE: true,
      SPRINT: false,
      VERSUS: false,
      BRICKFALL_SOLO: false,
        ROGUELIKE: false,
      ROGUELIKE_VERSUS: false,
      PUZZLE: false,
      TETROMAZE: false,
    },
    tetrobotAffinityLedger: {
      play_regularly: 0,
      rage_quit: 0,
      improve_stat: 0,
      repeat_mistake: 0,
      challenge_yourself: 0,
      avoid_weakness: 0,
    },
    tetrobotMemories: {
      rookie: [],
      pulse: [],
      apex: [],
    },
    tetrobotProgression: {
      rookie: { level: 1 as const, xp: 0, affinity: 0, mood: "neutral" as const, unlockedTraits: [] },
      pulse: { level: 1 as const, xp: 0, affinity: 0, mood: "neutral" as const, unlockedTraits: [] },
      apex: { level: 1 as const, xp: 0, affinity: -70, mood: "angry" as const, unlockedTraits: [] },
    },
    tetrobotXpLedger: {
      play_game: 0,
      win_game: 0,
      try_new_mode: 0,
      fail_repeated: 0,
      improve_stat: 0,
    },
    tetromazeEscapesTotal: 0,
    activeTetrobotChallenge: null,
    lastTetrobotLevelUp: null,
  };
}

describe("tetrobotProgressionLogic", () => {
  it("creates Apex trust-break memory and challenge when trust is refusing", () => {
    const result = syncTetrobotProgressionState(createBaseStats());

    expect(result.changed).toBe(true);
    expect(result.tetrobotMemories.apex.some((entry) => entry.type === "trust_break")).toBe(true);
    expect(result.activeTetrobotChallenge?.bot).toBe("apex");
    expect(result.activeTetrobotChallenge?.status).toBe("offered");
    expect(result.counterDeltas.apex_refusal_count).toBe(1);
  });

  it("emits Pulse advice-success counter when improvement signals grow", () => {
    const stats = createBaseStats();
    stats.level10Modes.CLASSIQUE = true;
    stats.scoredModes.CLASSIQUE = true;
    stats.tetrobotXpLedger.improve_stat = 0;
    stats.tetrobotAffinityLedger.improve_stat = 0;

    const result = syncTetrobotProgressionState(stats);

    expect(result.counterDeltas.pulse_advice_success).toBe(1);
    expect(result.tetrobotMemories.pulse.some((entry) => entry.type === "player_progress")).toBe(
      true
    );
  });
});
