services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: "https://api.tetroworld.fr"
    container_name: tetris-frontend
    restart: always
    depends_on:
      - backend

    networks:
      - web

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.tetris.rule=Host(`tetroworld.fr`) || Host(`www.tetroworld.fr`)"
      - "traefik.http.routers.tetris.entrypoints=websecure"
      - "traefik.http.routers.tetris.tls.certresolver=letsencrypt"

      - "traefik.http.services.tetris.loadbalancer.server.port=5173"


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    container_name: tetris-backend
    restart: always

    env_file:
      - ./backend/.env
      - ./.env
    command: >
      sh -c "until npx prisma migrate deploy; do echo 'waiting for db'; sleep 2; done; npx prisma db seed; npm run start"
    depends_on:
      - db

    networks:
      - web

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.tetris-api.rule=Host(`api.tetroworld.fr`)"
      - "traefik.http.routers.tetris-api.entrypoints=websecure"
      - "traefik.http.routers.tetris-api.tls.certresolver=letsencrypt"

      - "traefik.http.services.tetris-api.loadbalancer.server.port=8080"


  db:
    image: postgres:16
    container_name: tetris-db
    restart: always

    environment:
      POSTGRES_USER: tetris_user
      POSTGRES_PASSWORD: tetris_pass
      POSTGRES_DB: tetris_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - internal


  adminer:
    image: adminer:4
    container_name: tetris-adminer
    restart: always

    environment:
      ADMINER_DEFAULT_SERVER: db

    networks:
      - internal


volumes:
  postgres_data:

networks:
  web:
    external: true

  internal: