FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

ENV DATABASE_URL=postgresql://tetris_user:tetris_pass@db:5432/tetris_db?schema=public

RUN npx prisma generate

ENV NODE_ENV=development
EXPOSE 8080
CMD ["npm", "run", "dev"]
