FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .


ENV NODE_ENV=development
EXPOSE 8080

CMD ["npm", "run", "dev"]
