FROM node:20-slim

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# Prisma + Dev mode
RUN npx prisma generate

ENV NODE_ENV=development
EXPOSE 8080

CMD ["npm", "run", "dev"]
