ALTER TYPE "GameMode" ADD VALUE IF NOT EXISTS 'PIXEL_INVASION';

CREATE TABLE IF NOT EXISTS "PixelInvasionProgress" (
  "userId" INTEGER NOT NULL,
  "highestWave" INTEGER NOT NULL DEFAULT 1,
  "currentWave" INTEGER NOT NULL DEFAULT 1,
  "bestScore" INTEGER NOT NULL DEFAULT 0,
  "totalKills" INTEGER NOT NULL DEFAULT 0,
  "totalLineBursts" INTEGER NOT NULL DEFAULT 0,
  "victories" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "PixelInvasionProgress_pkey" PRIMARY KEY ("userId")
);

ALTER TABLE "PixelInvasionProgress"
  ADD CONSTRAINT "PixelInvasionProgress_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
