import { TILE } from "./constants";
import {
  apexClimbPattern,
  checkpointPattern,
  enemyPattern,
  glitchBridgePattern,
  hackGatePattern,
  orbOnTile,
  orbPattern,
  platformPattern,
  skillOrbOnTile,
  staircasePattern,
  sortLevels,
} from "./levelBuilders";
import type { LevelDef } from "./types";

/*
  Guide rapide pour ajouter un niveau Pixel Protocol

  1. Ajouter un nouvel objet dans `rawLevels` avec :
     - `id`: format `w<monde>-<niveau>` comme `w2-3`
     - `world`: numero du monde
     - `name`: nom affiche dans le HUD
     - `worldWidth`: largeur logique du niveau, en general `nombreDeTuiles * TILE`
     - `requiredOrbs`: nombre d'orbs necessaires pour ouvrir le portail
     - `spawn`: position de depart du joueur, en pixels
     - `portal`: position du portail de fin, en pixels
     - `platforms`, `checkpoints`, `orbs`, `enemies`

  2. Positionnement :
     - Les plateformes sont placees en coordonnees de grille, pas en pixels.
       Exemple : `x: 10, y: 14` signifie "10 tuiles depuis la gauche, 14 tuiles depuis le haut".
     - Plus `y` est petit, plus la plateforme est haute.
     - `spawn`, `portal`, `orbOnTile`, `checkpointPattern` et `enemyOnITop`
       convertissent ensuite vers des positions pixels si necessaire.

  3. Builders utiles :
     - `platformPattern(...)` :
       pour poser explicitement chaque plateforme ou `i-span`
     - `staircasePattern(...)` :
       pour decrire une progression relative avec `dx` / `dy`
     - `orbPattern(...)`, `checkpointPattern(...)`, `enemyPattern(...)` :
       pour generer rapidement les autres elements repetitifs
     - `glitchBridgePattern(...)`, `hackGatePattern(...)`, `apexClimbPattern(...)` :
       pour reutiliser des motifs deja employes dans les mondes avances

  4. Placement des elements :
     - `checkpoints` :
       place-les sur une plateforme stable ou facile a retrouver apres une chute
     - `orbs` :
       place-les legerement en avant du trajet principal ou sur une petite prise de risque
     - `enemies` :
       utilise `enemyPattern(...)` ou `enemyOnITop(...)` avec l'ancre d'une plateforme de type `I`
       ou d'une zone de sol assez lisible pour leur patrouille
     - `portal` :
       place-le sur la derniere portion jouable, jamais a l'interieur d'une plateforme

  5. Reglage du gameplay :
     - Si un saut est trop difficile, prefere d'abord reduire l'ecart horizontal entre plateformes
       plutot qu'ajouter une plateforme supplementaire.
     - Dans les mondes 1 et 2, garde des sauts assez lisibles.
       Les mondes 3 et 4 peuvent etre plus denses, mais doivent rester jouables sans pixel-perfect.
*/
const rawLevels = [
  {
    id: "w1-1",
    world: 1,
    name: "Bloc Stable",
    worldWidth: 96 * TILE,
    requiredOrbs: 7,
    spawn: { x: 96, y: 450 },
    portal: { x: 2460, y: 260 },
    platforms: platformPattern("p", [
      { kind: "i-span", x: 5, y: 15, type: "stable", count: 2 },
      { tetromino: "T", x: 10, y: 14, type: "stable" },
      { tetromino: "I", x: 15, y: 14, type: "stable" },
      { tetromino: "L", x: 20, y: 13, type: "bounce" },
      { tetromino: "O", x: 25, y: 13, type: "stable" },
      { kind: "i-span", x: 31, y: 12, type: "stable", count: 2 },
      { tetromino: "T", x: 37, y: 12, type: "stable" },
      { tetromino: "L", x: 43, y: 11, type: "bounce" },
      { tetromino: "I", x: 49, y: 11, type: "stable" },
      { tetromino: "O", x: 56, y: 10, type: "stable" },
      { tetromino: "I", x: 63, y: 10, type: "stable" },
      { tetromino: "T", x: 71, y: 9, type: "stable" },
    ]),
    checkpoints: checkpointPattern("c", [
      [16, 14],
      [44, 11],
      [63, 10],
    ]),
    orbs: orbPattern("o", [
      [6, 15],
      [11, 14],
      [21, 13],
      [32, 12],
      [44, 11],
      [57, 10],
      [72, 9],
    ]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 5, anchorY: 15, speed: 70, dir: 1, spanI: 2 },
      { kind: "rookie", anchorX: 31, anchorY: 12, speed: 75, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w1-2",
    world: 1,
    name: "Twin Ladders",
    worldWidth: 108 * TILE,
    requiredOrbs: 8,
    spawn: { x: 96, y: 450 },
    portal: { x: 2750, y: 210 },
    platforms: platformPattern("p", [
      { tetromino: "I", x: 5, y: 15, type: "stable" },
      { tetromino: "T", x: 11, y: 14, type: "stable" },
      { tetromino: "L", x: 18, y: 13, type: "bounce" },
      { kind: "i-span", x: 24, y: 12, type: "stable", count: 2 },
      { tetromino: "O", x: 35, y: 11, type: "stable" },
      { tetromino: "T", x: 41, y: 10, type: "stable" },
      { tetromino: "L", x: 47, y: 9, type: "bounce" },
      { kind: "i-span", x: 54, y: 8, type: "stable", count: 2 },
      { tetromino: "O", x: 61, y: 7, type: "stable" },
      { tetromino: "O", x: 68, y: 7, type: "stable" },
      { tetromino: "I", x: 75, y: 7, type: "stable" },
      { tetromino: "T", x: 82, y: 6, type: "stable" },
      { kind: "i-span", x: 89, y: 8, type: "stable", count: 2 },
    ]),
    checkpoints: checkpointPattern("c", [
      [24, 12],
      [47, 9],
      [88, 6],
    ]),
    orbs: [
      ...orbPattern("o", [
        [6, 15],
        [12, 14],
        [19, 13],
        [36, 11],
        [41, 10],
        [47, 9],
        [61, 7],
        [68, 7],
      ]),
      skillOrbOnTile("s1", 47, 8, "OVERJUMP", "blue"),
      orbOnTile("o7b", 76, 7),
      orbOnTile("o8", 90, 8),
    ],
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 5, anchorY: 15, speed: 72, dir: 1, spanI: 1 },
      { kind: "rookie", anchorX: 24, anchorY: 12, speed: 78, dir: -1, spanI: 2 },
      { kind: "rookie", anchorX: 54, anchorY: 8, speed: 82, dir: 1, spanI: 2 },
      { kind: "rookie", anchorX: 75, anchorY: 7, speed: 84, dir: -1, spanI: 1 },
    ]),
  },
  {
    id: "w1-3",
    world: 1,
    name: "Bounce Relay",
    worldWidth: 116 * TILE,
    requiredOrbs: 9,
    spawn: { x: 96, y: 450 },
    portal: { x: 3230, y: 176 },
    platforms: platformPattern("p", [
      { tetromino: "I", x: 4, y: 15, type: "stable" },
      { tetromino: "S", x: 10, y: 14, type: "bounce" },
      { tetromino: "O", x: 18, y: 13, type: "stable" },
      { tetromino: "L", x: 25, y: 12, type: "bounce" },
      { kind: "i-span", x: 29, y: 11, type: "stable", count: 2 },
      { tetromino: "T", x: 36, y: 10, type: "stable" },
      { tetromino: "L", x: 43, y: 9, type: "bounce" },
      { tetromino: "O", x: 50, y: 8, type: "stable" },
      { kind: "i-span", x: 56, y: 7, type: "stable", count: 2 },
      { tetromino: "T", x: 65, y: 6, type: "stable" },
      { kind: "i-span", x: 72, y: 7, type: "stable", count: 2 },
    ]),
    checkpoints: checkpointPattern("c", [
      [25, 12],
      [43, 9],
      [65, 6],
    ]),
    orbs: orbPattern("o", [
      [5, 15],
      [11, 14],
      [19, 13],
      [26, 12],
      [30, 11],
      [44, 9],
      [51, 8],
      [57, 7],
      [73, 7],
    ]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 76, dir: 1, spanI: 1 },
      { kind: "rookie", anchorX: 29, anchorY: 11, speed: 82, dir: -1, spanI: 2 },
      { kind: "rookie", anchorX: 56, anchorY: 7, speed: 88, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w1-4",
    world: 1,
    name: "Overhang Array",
    worldWidth: 124 * TILE,
    requiredOrbs: 10,
    spawn: { x: 96, y: 450 },
    portal: { x: 3520, y: 146 },
    platforms: platformPattern("p", [
      { kind: "i-span", x: 5, y: 15, type: "stable", count: 2 },
      { tetromino: "T", x: 14, y: 14, type: "stable" },
      { tetromino: "L", x: 21, y: 13, type: "bounce" },
      { tetromino: "O", x: 28, y: 12, type: "stable" },
      { kind: "i-span", x: 35, y: 11, type: "stable", count: 2 },
      { tetromino: "S", x: 45, y: 10, type: "bounce" },
      { tetromino: "T", x: 53, y: 9, type: "stable" },
      { tetromino: "L", x: 62, y: 8, type: "bounce" },
      { kind: "i-span", x: 70, y: 7, type: "stable", count: 2 },
      { tetromino: "O", x: 81, y: 6, type: "stable" },
      { tetromino: "T", x: 90, y: 5, type: "stable" },
      { kind: "i-span", x: 98, y: 6, type: "stable", count: 2 },
    ]),
    checkpoints: checkpointPattern("c", [
      [28, 12],
      [53, 9],
      [81, 6],
    ]),
    orbs: orbPattern("o", [
      [6, 15],
      [15, 14],
      [22, 13],
      [29, 12],
      [36, 11],
      [46, 10],
      [63, 8],
      [71, 7],
      [82, 6],
      [99, 6],
    ]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 5, anchorY: 15, speed: 80, dir: 1, spanI: 2 },
      { kind: "rookie", anchorX: 35, anchorY: 11, speed: 86, dir: -1, spanI: 2 },
      { kind: "rookie", anchorX: 70, anchorY: 7, speed: 90, dir: 1, spanI: 2 },
      { kind: "rookie", anchorX: 98, anchorY: 6, speed: 92, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w1-5",
    world: 1,
    name: "Skyline Stack",
    worldWidth: 132 * TILE,
    requiredOrbs: 11,
    spawn: { x: 96, y: 450 },
    portal: { x: 3790, y: 112 },
    platforms: platformPattern("p", [
      { tetromino: "I", x: 4, y: 15, type: "stable" },
      { tetromino: "T", x: 10, y: 14, type: "stable" },
      { tetromino: "L", x: 17, y: 13, type: "bounce" },
      { tetromino: "O", x: 24, y: 12, type: "stable" },
      { kind: "i-span", x: 31, y: 11, type: "stable", count: 2 },
      { tetromino: "L", x: 41, y: 10, type: "bounce" },
      { tetromino: "T", x: 49, y: 9, type: "stable" },
      { tetromino: "O", x: 57, y: 8, type: "stable" },
      { kind: "i-span", x: 65, y: 7, type: "stable", count: 2 },
      { tetromino: "L", x: 76, y: 6, type: "bounce" },
      { tetromino: "T", x: 84, y: 5, type: "stable" },
      { tetromino: "O", x: 92, y: 4, type: "stable" },
      { kind: "i-span", x: 99, y: 5, type: "stable", count: 2 },
    ]),
    checkpoints: checkpointPattern("c", [
      [24, 12],
      [57, 8],
      [84, 5],
    ]),
    orbs: orbPattern("o", [
      [5, 15],
      [11, 14],
      [18, 13],
      [25, 12],
      [32, 11],
      [42, 10],
      [58, 8],
      [66, 7],
      [77, 6],
      [93, 4],
      [100, 5],
    ]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 82, dir: 1, spanI: 1 },
      { kind: "rookie", anchorX: 31, anchorY: 11, speed: 88, dir: -1, spanI: 2 },
      { kind: "rookie", anchorX: 65, anchorY: 7, speed: 94, dir: 1, spanI: 2 },
      { kind: "rookie", anchorX: 99, anchorY: 5, speed: 96, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w2-1",
    world: 2,
    name: "Glitch Sector",
    worldWidth: 104 * TILE,
    requiredOrbs: 8,
    spawn: { x: 120, y: 450 },
    portal: { x: 3160, y: 286 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "stable" },
      { tetromino: "S", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 2300 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "stable", dx: 7, dy: -1 },
      { tetromino: "I", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 2200 },
      { tetromino: "L", type: "glitch", dx: 8, dy: 1 },
      { kind: "i-span", count: 2, type: "stable", dx: 8, dy: -1 },
      { tetromino: "S", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "O", type: "stable", dx: 8, dy: 1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: 1, rotateEveryMs: 2000 },
      { kind: "i-span", count: 2, type: "stable", dx: 8, dy: 0 },
    ]),
    checkpoints: checkpointPattern("c", [[18, 13], [48, 9], [80, 9]]),
    orbs: orbPattern("o", [[5, 15], [12, 14], [19, 13], [33, 11], [48, 9], [64, 9], [80, 9], [96, 10]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 80, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 63, anchorY: 9, speed: 95, dir: -1, spanI: 2 },
      { kind: "pulse", anchorX: 95, anchorY: 10, speed: 100, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w2-2",
    world: 2,
    name: "Static Drift",
    worldWidth: 118 * TILE,
    requiredOrbs: 9,
    spawn: { x: 110, y: 450 },
    portal: { x: 3340, y: 180 },
    platforms: staircasePattern("p", 4, 15, [
      { tetromino: "I", type: "stable" },
      { tetromino: "S", type: "glitch", dx: 6, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 2200 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "grapplable", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 7, dy: -1 },
      { tetromino: "T", type: "grapplable", dx: 10, dy: -1 },
      { tetromino: "L", type: "grapplable", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "grapplable", dx: 8, dy: -1 },
      { tetromino: "S", type: "grapplable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1900 },
      { kind: "i-span", count: 2, type: "grapplable", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[18, 13], [56, 9], [89, 6]]),
    orbs: [
      ...orbPattern("o", [[5, 15], [11, 14], [19, 13], [35, 11], [43, 10], [67, 8], [77, 7], [90, 6]]),
      skillOrbOnTile("s0", 56, 9, "DATA_GRAPPLE", "blue"),
      skillOrbOnTile("s1", 98, 5, "OVERCLOCK_MODE", "blue"),
      skillOrbOnTile("s2", 74, 7, "TIME_BUFFER", "purple"),
      orbOnTile("o9", 110, 6),
    ],
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 86, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 42, anchorY: 10, speed: 102, dir: -1, spanI: 2 },
      { kind: "rookie", anchorX: 76, anchorY: 7, speed: 92, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 109, anchorY: 6, speed: 112, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w2-3",
    world: 2,
    name: "Shattered Switchback",
    worldWidth: 126 * TILE,
    requiredOrbs: 10,
    spawn: { x: 110, y: 450 },
    portal: { x: 3620, y: 146 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "stable" },
      { tetromino: "S", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 2100 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "stable", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
      { tetromino: "L", type: "glitch", dx: 11, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1980 },
      { kind: "i-span", count: 2, type: "stable", dx: 9, dy: -1 },
      { tetromino: "S", type: "unstable", dx: 11, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 9, dy: -1, rotateEveryMs: 1820 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
    ]),
    checkpoints: checkpointPattern("c", [[21, 13], [60, 9], [95, 6]]),
    orbs: orbPattern("o", [[5, 15], [14, 14], [22, 13], [38, 11], [47, 10], [61, 9], [71, 8], [82, 7], [96, 6], [117, 4]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 88, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 46, anchorY: 10, speed: 106, dir: -1, spanI: 2 },
      { kind: "pulse", anchorX: 81, anchorY: 7, speed: 112, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w2-4",
    world: 2,
    name: "Rotor Spine",
    worldWidth: 136 * TILE,
    requiredOrbs: 11,
    spawn: { x: 110, y: 450 },
    portal: { x: 3940, y: 112 },
    platforms: staircasePattern("p", 5, 15, [
      { tetromino: "I", type: "stable" },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 2200 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "stable", dx: 7, dy: -1 },
      { tetromino: "S", type: "glitch", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1950 },
      { tetromino: "L", type: "glitch", dx: 9, dy: -1 },
      { kind: "i-span", count: 2, type: "stable", dx: 9, dy: -1 },
      { tetromino: "Z", type: "unstable", dx: 12, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 9, dy: -1, rotateEveryMs: 1700 },
      { tetromino: "L", type: "glitch", dx: 9, dy: -1 },
      { kind: "i-span", count: 2, type: "stable", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[28, 12], [59, 9], [96, 6]]),
    orbs: orbPattern("o", [[6, 15], [13, 14], [21, 13], [29, 12], [37, 11], [46, 10], [71, 8], [82, 7], [97, 6], [119, 4], [128, 5]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 5, anchorY: 15, speed: 90, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 45, anchorY: 10, speed: 110, dir: -1, spanI: 2 },
      { kind: "pulse", anchorX: 81, anchorY: 7, speed: 118, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 127, anchorY: 5, speed: 122, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w2-5",
    world: 2,
    name: "Ghost Lattice",
    worldWidth: 144 * TILE,
    requiredOrbs: 12,
    spawn: { x: 110, y: 450 },
    portal: { x: 4200, y: 80 },
    platforms: staircasePattern("p", 4, 15, [
      { tetromino: "I", type: "stable" },
      { tetromino: "S", type: "glitch", dx: 6, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 2100 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "stable", dx: 7, dy: -1 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1880 },
      { tetromino: "L", type: "glitch", dx: 9, dy: -1 },
      { kind: "i-span", count: 2, type: "stable", dx: 9, dy: -1 },
      { tetromino: "S", type: "unstable", dx: 12, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 9, dy: -1, rotateEveryMs: 1700 },
      { tetromino: "L", type: "glitch", dx: 9, dy: -1 },
      { kind: "i-span", count: 2, type: "stable", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[34, 11], [68, 8], [105, 5]]),
    orbs: orbPattern("o", [[5, 15], [11, 14], [19, 13], [35, 11], [44, 10], [54, 9], [69, 8], [80, 7], [91, 6], [106, 5], [128, 3], [137, 4]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 92, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 53, anchorY: 9, speed: 112, dir: -1, spanI: 2 },
      { kind: "pulse", anchorX: 90, anchorY: 6, speed: 120, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 136, anchorY: 4, speed: 126, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w3-1",
    world: 3,
    name: "Corrupted Grid",
    worldWidth: 112 * TILE,
    requiredOrbs: 9,
    spawn: { x: 110, y: 450 },
    portal: { x: 3406, y: 212 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "hackable" },
      { tetromino: "J", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1800 },
      { tetromino: "L", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 7, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1700 },
      { tetromino: "L", type: "glitch", dx: 7, dy: 1 },
      { tetromino: "Z", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "O", type: "armored", dx: 7, dy: 1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 7, dy: 1 },
      { tetromino: "T", type: "bounce", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
    ]),
    checkpoints: checkpointPattern("c", [[19, 13], [51, 9], [91, 10]]),
    orbs: orbPattern("o", [[5, 15], [12, 14], [19, 13], [35, 11], [51, 9], [59, 8], [75, 8], [91, 10], [107, 8]]),
    enemies: enemyPattern("e", [
      { kind: "pulse", anchorX: 4, anchorY: 15, speed: 110, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 50, anchorY: 9, speed: 115, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 90, anchorY: 10, speed: 140, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w3-2",
    world: 3,
    name: "Hackline Rise",
    worldWidth: 124 * TILE,
    requiredOrbs: 10,
    spawn: { x: 110, y: 450 },
    portal: { x: 3550, y: 146 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "hackable" },
      { tetromino: "J", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1760 },
      { tetromino: "L", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 12, dy: -1, rotateEveryMs: 1650 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "Z", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[21, 13], [57, 9], [92, 6]]),
    orbs: [
      ...orbPattern("o", [[5, 15], [14, 14], [22, 13], [39, 11], [48, 10], [58, 9], [73, 8], [83, 7], [112, 6]]),
      skillOrbOnTile("s1", 103, 5, "PHASE_SHIFT", "purple"),
      skillOrbOnTile("s2", 66, 8, "PLATFORM_SPAWN", "green"),
    ],
    enemies: enemyPattern("e", [
      { kind: "pulse", anchorX: 4, anchorY: 15, speed: 112, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 57, anchorY: 9, speed: 118, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 111, anchorY: 6, speed: 145, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w3-3",
    world: 3,
    name: "Cipher Ramparts",
    worldWidth: 134 * TILE,
    requiredOrbs: 11,
    spawn: { x: 110, y: 450 },
    portal: { x: 3870, y: 112 },
    platforms: staircasePattern("p", 4, 15, [
      { tetromino: "I", type: "hackable" },
      { tetromino: "J", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1750 },
      { tetromino: "L", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 12, dy: -1, rotateEveryMs: 1620 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "Z", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "bounce", dx: 10, dy: 1 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
    ]),
    checkpoints: checkpointPattern("c", [[19, 13], [55, 9], [100, 5]]),
    orbs: orbPattern("o", [[5, 15], [12, 14], [20, 13], [37, 11], [46, 10], [56, 9], [71, 8], [81, 7], [101, 5], [110, 4], [130, 4]]),
    enemies: enemyPattern("e", [
      { kind: "pulse", anchorX: 4, anchorY: 15, speed: 114, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 55, anchorY: 9, speed: 121, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 109, anchorY: 4, speed: 150, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w3-4",
    world: 3,
    name: "Glitch Bastion",
    worldWidth: 144 * TILE,
    requiredOrbs: 12,
    spawn: { x: 110, y: 450 },
    portal: { x: 4180, y: 80 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "hackable" },
      { tetromino: "J", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1720 },
      { tetromino: "L", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 12, dy: -1, rotateEveryMs: 1600 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "Z", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1500 },
      { tetromino: "O", type: "armored", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[22, 13], [58, 9], [103, 5]]),
    orbs: orbPattern("o", [[5, 15], [15, 14], [23, 13], [40, 11], [49, 10], [59, 9], [74, 8], [84, 7], [104, 5], [113, 4], [127, 3], [137, 4]]),
    enemies: enemyPattern("e", [
      { kind: "pulse", anchorX: 4, anchorY: 15, speed: 116, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 58, anchorY: 9, speed: 123, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 112, anchorY: 4, speed: 152, dir: 1, spanI: 2 },
      { kind: "apex", anchorX: 136, anchorY: 4, speed: 160, dir: -1, spanI: 1 },
    ]),
  },
  {
    id: "w3-5",
    world: 3,
    name: "Kernel Vault",
    worldWidth: 152 * TILE,
    requiredOrbs: 13,
    spawn: { x: 110, y: 450 },
    portal: { x: 4420, y: 50 },
    platforms: staircasePattern("p", 4, 15, [
      { tetromino: "I", type: "hackable" },
      { tetromino: "J", type: "rotating", dx: 6, dy: -1, rotateEveryMs: 1700 },
      { tetromino: "L", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "T", type: "unstable", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 12, dy: -1, rotateEveryMs: 1580 },
      { tetromino: "L", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "Z", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1480 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "hackable", dx: 8, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[18, 13], [54, 9], [99, 5]]),
    orbs: orbPattern("o", [[5, 15], [11, 14], [19, 13], [36, 11], [45, 10], [55, 9], [70, 8], [80, 7], [90, 6], [100, 5], [109, 4], [133, 2], [146, 3]]),
    enemies: enemyPattern("e", [
      { kind: "pulse", anchorX: 4, anchorY: 15, speed: 118, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 54, anchorY: 9, speed: 124, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 108, anchorY: 4, speed: 156, dir: 1, spanI: 2 },
      { kind: "apex", anchorX: 141, anchorY: 3, speed: 164, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w4-1",
    world: 4,
    name: "Apex Core",
    worldWidth: 120 * TILE,
    requiredOrbs: 10,
    spawn: { x: 110, y: 450 },
    portal: { x: 3640, y: 240 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "stable" },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1600 },
      { tetromino: "L", type: "hackable", dx: 7, dy: -1 },
      { tetromino: "J", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
      { tetromino: "Z", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1450 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
      { tetromino: "I", type: "unstable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1400 },
      { tetromino: "L", type: "hackable", dx: 8, dy: 1 },
      { tetromino: "S", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: 1 },
      { kind: "i-span", count: 2, type: "bounce", dx: 8, dy: 1 },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1350 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "stable", dx: 2, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[19, 13], [55, 8], [95, 9]]),
    orbs: orbPattern("o", [[5, 15], [12, 14], [19, 13], [33, 11], [47, 9], [55, 8], [63, 7], [79, 7], [95, 9], [111, 7]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 100, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 94, anchorY: 9, speed: 130, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 112, anchorY: 8, speed: 170, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w4-2",
    world: 4,
    name: "Apex Relay",
    worldWidth: 132 * TILE,
    requiredOrbs: 11,
    spawn: { x: 110, y: 450 },
    portal: { x: 3780, y: 112 },
    platforms: staircasePattern("p", 4, 15, [
      { kind: "i-span", count: 2, type: "stable" },
      { tetromino: "T", type: "rotating", dx: 8, dy: -1, rotateEveryMs: 1550 },
      { tetromino: "L", type: "hackable", dx: 7, dy: -1 },
      { tetromino: "J", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
      { tetromino: "Z", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1450 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1380 },
      { tetromino: "L", type: "hackable", dx: 8, dy: 1 },
      { tetromino: "S", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "bounce", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 10, dy: -1, rotateEveryMs: 1320 },
    ]),
    checkpoints: checkpointPattern("c", [[19, 13], [60, 8], [102, 6]]),
    orbs: [
      ...orbPattern("o", [[5, 15], [13, 14], [20, 13], [36, 11], [44, 10], [52, 9], [61, 8], [75, 7], [94, 7], [124, 4]]),
      skillOrbOnTile("s1", 103, 6, "PULSE_SHOCK", "red"),
    ],
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 102, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 60, anchorY: 8, speed: 132, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 111, anchorY: 5, speed: 172, dir: 1, spanI: 2 },
    ]),
  },
  {
    id: "w4-3",
    world: 4,
    name: "Prism Furnace",
    worldWidth: 142 * TILE,
    requiredOrbs: 12,
    spawn: { x: 110, y: 450 },
    portal: { x: 4100, y: 80 },
    platforms: staircasePattern("p", 4, 15, [
      { tetromino: "I", type: "stable" },
      { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1520 },
      { tetromino: "L", type: "hackable", dx: 7, dy: -1 },
      { tetromino: "J", type: "glitch", dx: 7, dy: -1 },
      { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
      { tetromino: "Z", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1430 },
      { tetromino: "O", type: "armored", dx: 7, dy: -1 },
      { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1370 },
      { tetromino: "L", type: "hackable", dx: 8, dy: -1 },
      { tetromino: "S", type: "glitch", dx: 8, dy: -1 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { kind: "i-span", count: 2, type: "bounce", dx: 8, dy: -1 },
      { tetromino: "T", type: "rotating", dx: 10, dy: 1, rotateEveryMs: 1290 },
      { tetromino: "O", type: "armored", dx: 8, dy: -1 },
      { tetromino: "I", type: "stable", dx: 5, dy: 1 },
    ]),
    checkpoints: checkpointPattern("c", [[18, 13], [59, 8], [101, 4]]),
    orbs: orbPattern("o", [[5, 15], [12, 14], [19, 13], [35, 11], [43, 10], [51, 9], [60, 8], [74, 7], [93, 5], [102, 4], [111, 3], [138, 4]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 104, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 59, anchorY: 8, speed: 136, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 110, anchorY: 3, speed: 176, dir: 1, spanI: 2 },
      { kind: "apex", anchorX: 137, anchorY: 4, speed: 182, dir: -1, spanI: 1 },
    ]),
  },
  {
    id: "w4-4",
    world: 4,
    name: "Singularity Steps",
    worldWidth: 152 * TILE,
    requiredOrbs: 13,
    spawn: { x: 110, y: 450 },
    portal: { x: 4410, y: 50 },
    platforms: [
      ...staircasePattern("p", 4, 15, [
        { kind: "i-span", count: 2, type: "stable" },
        { tetromino: "T", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1500 },
        { tetromino: "L", type: "hackable", dx: 7, dy: -1 },
        { tetromino: "J", type: "glitch", dx: 7, dy: -1 },
        { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
        { tetromino: "Z", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1410 },
        { tetromino: "O", type: "armored", dx: 7, dy: -1 },
        { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
        { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1360 },
        { tetromino: "L", type: "hackable", dx: 8, dy: -1 },
      ]),
      ...glitchBridgePattern("gb", 94, 5),
      ...apexClimbPattern("ac", 125, 2, { rotateEveryMs: 1280 }),
    ],
    checkpoints: checkpointPattern("c", [[20, 13], [61, 8], [103, 4]]),
    orbs: orbPattern("o", [[5, 15], [13, 14], [21, 13], [37, 11], [45, 10], [53, 9], [62, 8], [76, 7], [95, 5], [104, 4], [113, 3], [135, 1], [147, 2]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 106, dir: 1, spanI: 2 },
      { kind: "pulse", anchorX: 61, anchorY: 8, speed: 138, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 112, anchorY: 3, speed: 178, dir: 1, spanI: 2 },
      { kind: "apex", anchorX: 142, anchorY: 2, speed: 186, dir: -1, spanI: 2 },
    ]),
  },
  {
    id: "w4-5",
    world: 4,
    name: "Core Crown",
    worldWidth: 160 * TILE,
    requiredOrbs: 14,
    spawn: { x: 110, y: 450 },
    portal: { x: 4680, y: 20 },
    platforms: [
      ...staircasePattern("p", 4, 15, [
        { tetromino: "I", type: "stable" },
        { tetromino: "T", type: "rotating", dx: 6, dy: -1, rotateEveryMs: 1480 },
        { tetromino: "L", type: "hackable", dx: 7, dy: -1 },
        { tetromino: "J", type: "glitch", dx: 7, dy: -1 },
        { tetromino: "S", type: "bounce", dx: 7, dy: -1 },
        { tetromino: "Z", type: "rotating", dx: 7, dy: -1, rotateEveryMs: 1390 },
        { tetromino: "O", type: "armored", dx: 7, dy: -1 },
        { kind: "i-span", count: 2, type: "unstable", dx: 8, dy: -1 },
        { tetromino: "T", type: "rotating", dx: 11, dy: -1, rotateEveryMs: 1340 },
        ...hackGatePattern("hg-inline", 83, 6).map((platform, index) => ({
          tetromino: platform.tetromino,
          type: platform.type,
          dx: index === 0 ? 8 : 7,
          dy: -1,
        })),
      ]),
      ...glitchBridgePattern("gb", 92, 5),
      ...apexClimbPattern("ac", 123, 2, {
        rotateEveryMs: 1270,
        finalDx: 7,
        finalDy: -1,
      }),
      ...staircasePattern("crown", 152, 1, [
        { tetromino: "T", type: "rotating", rotateEveryMs: 1220 },
        { tetromino: "O", type: "armored", dx: 4, dy: -1 },
      ]),
    ],
    checkpoints: checkpointPattern("c", [[18, 13], [59, 8], [101, 4]]),
    orbs: orbPattern("o", [[5, 15], [11, 14], [19, 13], [35, 11], [43, 10], [51, 9], [60, 8], [74, 7], [93, 5], [102, 4], [111, 3], [133, 1], [146, 0], [157, 0]]),
    enemies: enemyPattern("e", [
      { kind: "rookie", anchorX: 4, anchorY: 15, speed: 108, dir: 1, spanI: 1 },
      { kind: "pulse", anchorX: 59, anchorY: 8, speed: 140, dir: -1, spanI: 2 },
      { kind: "apex", anchorX: 110, anchorY: 3, speed: 180, dir: 1, spanI: 2 },
      { kind: "apex", anchorX: 141, anchorY: 0, speed: 188, dir: -1, spanI: 2 },
    ]),
  },
] satisfies LevelDef[];

export const LEVELS = sortLevels(rawLevels);
