CREATE TABLE "BotPlayerProfile" (
  "userId" INTEGER NOT NULL,
  "totalMatches" INTEGER NOT NULL DEFAULT 0,
  "avgStackHeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "avgHoles" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "avgCombo" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "tetrisRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "aggressionScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "defensiveScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "panicRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "leftBias" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "noHoldRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "matchesVsRookie" INTEGER NOT NULL DEFAULT 0,
  "matchesVsBalanced" INTEGER NOT NULL DEFAULT 0,
  "matchesVsApex" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "BotPlayerProfile_pkey" PRIMARY KEY ("userId")
);

ALTER TABLE "BotPlayerProfile"
ADD CONSTRAINT "BotPlayerProfile_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id")
ON DELETE RESTRICT ON UPDATE CASCADE;
